apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "sql-statefull-deploy.labels" . | nindent 4 }}
type: Opaque
data:
 SA_PASSWORD : {{ .Values.SA_PASSWORD | b64enc | quote}}