apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    {{- include "sql-statefull-deploy.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      name: mssql
  selector:
    {{- include "sql-statefull-deploy.selectorLabels" . | nindent 4 }}